- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create directory"
  shell: |
    mkdir backend

- name: "Unzip and navigate in actifact"
  unarchive:
    src: artifact.tar.gz
    dest: backend

- name: "launch app"
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
