- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Unzip and navigate in actifact"
  shell: |
    tar -czvf artifact.tar.gz backend
    cd backend

- name: "launch app"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
